# Starship prompt configuration
#
# Unicode reference:
#   \ue0b0 =  (powerline arrow right)
#   \ue0a0 =  (git branch)
#   \u2638 = ☸ (kubernetes wheel)
#   \U000f0399 = 󰎙 (nodejs)

format = """[\u2591\u2592\u2593](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[\ue0b0](bg:#769ff0 fg:#a3aed2)\
$directory\
[\ue0b0](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[\ue0b0](fg:#394260 bg:#2d344b)\
${custom.nodejs}\
[\ue0b0](fg:#2d344b)
$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = "\ue0a0"
style = "bg:#394260"
format = "[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)"

[git_status]
style = "bg:#394260"
format = "[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)"

[custom.nodejs]
command = "node --version | tr -d '\\n'"
when = true
symbol = "\U000f0399"
style = "bg:#2d344b"
format = "[[ $symbol $output ](fg:#769ff0 bg:#2d344b)]($style)"
disabled = false

[kubernetes]
symbol = "\u2638"
style = "bg:#212736"
format = "[[ $symbol ($context \\($namespace\\)) ](fg:#769ff0 bg:#212736)]($style)"
disabled = false
